[package]
name = "jump"
version = "0.1.0"
authors = ["Riley Quinn <merileyquinn@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.2.0"
dirs = "2.0.2"
regex = "1.3.1"
serde = "1.0.102"
serde_derive = "1.0.102"
toml = "0.5.5"